### ISSUE TITLE
ocl-tester.cpp does not build on g++ 4.8.2

### ISSUE THREAD

**Issue by toaarnio** [elhigu/opencl-testsuite#3]
It seems that ocl-tester.cpp is using some fancy new C++ features that may not be the most portable... Here's the output from "make", running g++ 4.8.2 under Cygwin:

```
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp: In function ‘std::string getDeviceString(const {anonymous}::DeviceInfo&)’:
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:183:25: error: ‘to_string’ is not a member of ‘std’
     return "{\"id\":" + std::to_string(device.deviceHash) + ",\"platformName\":\"" +
                         ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp: In function ‘std::string readAllInput()’:
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:199:5: error: ‘istream_iterator’ is not a member of ‘std’
     std::istream_iterator<char> begin(std::cin);
     ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:199:27: error: expected primary-expression before ‘char’
     std::istream_iterator<char> begin(std::cin);
                           ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:199:27: error: expected ‘;’ before ‘char’
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:200:5: error: ‘istream_iterator’ is not a member of ‘std’
     std::istream_iterator<char> end;
     ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:200:27: error: expected primary-expression before ‘char’
     std::istream_iterator<char> end;
                           ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:200:27: error: expected ‘;’ before ‘char’
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:201:24: error: ‘begin’ was not declared in this scope
     return std::string(begin, end);
                        ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:201:31: error: ‘end’ was not declared in this scope
     return std::string(begin, end);
                               ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp: In function ‘bool printDeviceInfo()’:
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:264:14: error: ‘next’ is not a member of ‘std’
         if ( std::next(iter) !=  devices.end() ) {
              ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp: In function ‘bool compileWithDevice(std::string, bool)’:
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:285:13: error: ‘to_string’ is not a member of ‘std’
         if (std::to_string(iter->second.deviceHash) == selectedDevice) {
             ^
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp: At global scope:
/cygdrive/c/work/opencl-testsuite/tools/ocl-tester/ocl-tester.cpp:312:3: warning: anonymous type with no linkage used to declare variable ‘<anonymous struct> Options’ with linkage [enabled by default]
 } Options = { "none", "none", false };
   ^
tools/ocl-tester/CMakeFiles/ocl-tester.dir/build.make:57: recipe for target 'tools/ocl-tester/CMakeFiles/ocl-tester.dir/ocl-tester.cpp.o' failed
make[2]: *** [tools/ocl-tester/CMakeFiles/ocl-tester.dir/ocl-tester.cpp.o] Error 1
```
